name: 'sync-npmmirror-action'
description: 'auto sync packages from npm to npmmirror'
author: 'SepVeneto'
inputs:
  name: # change this
    required: false
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node16'
  main: 'dist/index.js'
